// Artifact library — outputs completed agent tasks have produced.

export const ARTIFACTS = [
  {
    id: 'ART1',
    title: 'Strategy-to-Action — Q2 2026',
    type: 'pdf',
    agent: 'NOVA',
    taskType: 'Medical Insights Report',
    dateCreated: '2026-06-16',
    summary: 'Full Q2 Strategy-to-Action: ISP pillars, MO coverage, prioritised insights, proposed actions, and Gap Radar suggestions.',
    dataSources: ['MSL field notes', 'Ad board transcripts', 'Med Info queries', 'Congress debriefs', 'PubMed'],
    sizeLabel: '2.3 MB',
    provenance: 'synthesized',
  },
  {
    id: 'ART2',
    title: 'ATS 2026 Debrief — Tolerability & Sequencing Signals',
    type: 'pdf',
    agent: 'ARIA',
    taskType: 'Congress Debrief',
    dateCreated: '2026-05-22',
    summary: 'Synthesized read on the three dominant scientific themes at ATS 2026 — tolerability burden, nerandomilast sequencing, inhaled-category confusion — with competitor visibility and recommended actions.',
    dataSources: ['ATS 2026 abstracts', 'Session transcripts', 'Social commentary'],
    sizeLabel: '1.9 MB',
    provenance: 'synthesized',
  },
  {
    id: 'ART3',
    title: 'SSc-ILD Emerging KOL Map — June 2026',
    type: 'interactive',
    agent: 'LUCA',
    taskType: 'KOL Selection & Profiling',
    dateCreated: '2026-06-15',
    summary: 'Live KOL map with emerging-voice highlights and sentiment-shift overlays ahead of EULAR 2026. 2 new SSc-ILD names crossed the watch threshold this cycle.',
    dataSources: ['PubMed', 'Congress programs', 'CRM interaction history', 'Digital signals'],
    sizeLabel: 'In-app',
    provenance: 'synthesized',
  },
  {
    id: 'ART4',
    title: 'Tolerability/Adherence Conversation Guide v1',
    type: 'pptx',
    agent: 'NOVA',
    taskType: 'Medical Insights Report',
    dateCreated: '2026-06-10',
    summary: 'Field-ready conversation guide contrasting inhaled vs. oral GI/hepatic/dermatologic tolerability burden. Co-sourced from AI3.',
    dataSources: ['MSL field notes', 'Ad board transcripts'],
    sizeLabel: '2.8 MB',
    provenance: 'synthesized',
  },
  {
    id: 'ART5',
    title: 'EUSTAR-Aligned SSc-ILD Screening Algorithm — Draft',
    type: 'pdf',
    agent: 'NOVA',
    taskType: 'Evidence Generation',
    dateCreated: '2026-05-28',
    summary: 'Draft screening algorithm co-authored with rheumatology KOLs, scoped for EULAR 2026 advisory board review.',
    dataSources: ['Ad board transcripts', 'PubMed', 'EUSTAR registry references'],
    sizeLabel: '3.6 MB',
    provenance: 'synthesized',
  },
  {
    id: 'ART6',
    title: 'ATS 2026 → EULAR 2026 Sentiment Trend',
    type: 'interactive',
    agent: 'ARIA',
    taskType: 'Congress Intelligence',
    dateCreated: '2026-06-01',
    summary: 'Cross-congress sentiment shift across scientific themes, competitor visibility, and social amplification, bridging pulmonology and rheumatology audiences.',
    dataSources: ['ATS 2026 abstracts', 'EULAR 2026 pre-program', 'Social commentary'],
    sizeLabel: 'In-app',
    provenance: 'synthesized',
  },
];
