// Actionable insights — Demo Brief §5.

export const INSIGHTS = [
  {
    id: 'AI1',
    title: 'MIST / CTD-ILD referral pathway confusion',
    priority: 'High',
    lpRefs: ['LP1'], moRefs: ['MO1'],
    recurrence: 3,
    recency: '2026-06',
    summary: 'Community rheumatologists are unsure how to route CTD-ILD patients into MIST trial sites; pulmonology and rheumatology referral language is inconsistent across territories.',
    sourceInsights: [
      { type: 'MSL interaction', role: 'Community rheumatologist', location: 'Boston, MA', quote: 'I know MIST exists but I don\'t know which of my SSc-ILD patients would qualify, or who to call.', date: '2026-06-04' },
      { type: 'Congress debrief', role: 'ILD center director', location: 'ATS 2026', quote: 'Referral into inhaled-antifibrotic trials needs a much clearer front door for community rheum.', date: '2026-05-18' },
      { type: 'Med Info query', role: 'Rheumatology fellow', location: 'Leeds, UK', quote: 'Asked for a one-page eligibility checklist for MIST before referring a patient.', date: '2026-06-11' },
    ],
    status: 'Prioritised',
    confidenceScore: 0.85,
    provenance: 'synthesized',
  },
  {
    id: 'AI2',
    title: 'Inhaled PK rationale unclear to community pulmonologists',
    priority: 'High',
    lpRefs: ['LP2'], moRefs: ['MO2'],
    recurrence: 2,
    recency: '2026-06',
    summary: 'Community pulmonologists want a plain-language explanation of why inhaled delivery reduces systemic exposure before they engage further on AURA-IPF; several push back on unqualified exposure-reduction claims.',
    sourceInsights: [
      { type: 'MSL interaction', role: 'Community pulmonologist', location: 'Chicago, IL', quote: 'If you tell me it\'s 15 to 68 times lower exposure I want to know whose number that is and how it was measured.', date: '2026-06-08' },
      { type: 'Ad board', role: 'Academic pulmonologist', location: 'Virtual', quote: 'The PK story is compelling but needs to be presented as company data until it\'s independently replicated.', date: '2026-05-22' },
    ],
    status: 'Validated',
    confidenceScore: 0.81,
    provenance: 'synthesized',
  },
  {
    id: 'AI3',
    title: 'Tolerability burden is the #1 discontinuation driver in conversation',
    priority: 'High',
    lpRefs: ['LP3'], moRefs: ['MO3'],
    recurrence: 4,
    recency: '2026-06',
    summary: 'Pulmonologists consistently cite GI and dermatologic adverse events as the leading reason patients ask about alternatives to oral pirfenidone/nintedanib — the highest-recurrence theme this cycle.',
    sourceInsights: [
      { type: 'MSL interaction', role: 'Community pulmonologist', location: 'Durham, NC', quote: 'Nausea and rash are why patients stop calling me back, not lack of efficacy.', date: '2026-06-10' },
      { type: 'Ad board', role: 'Academic pulmonologist', location: 'Cleveland, OH', quote: 'I counsel every new Ofev patient that diarrhea is basically guaranteed. That conversation alone costs adherence.', date: '2026-05-29' },
      { type: 'Congress debrief', role: 'ILD nurse coordinator', location: 'ATS 2026', quote: 'Patients ask us for anything that avoids the GI side effects — an inhaled option is an easy yes if it works.', date: '2026-05-17' },
      { type: 'Med Info query', role: 'Community pulmonologist', location: 'Zurich, Switzerland', quote: 'Requested adherence/discontinuation data comparing inhaled vs oral delivery route, not just efficacy.', date: '2026-06-15' },
    ],
    status: 'Prioritised',
    confidenceScore: 0.89,
    provenance: 'synthesized',
  },
  {
    id: 'AI4',
    title: 'SSc-ILD patients reaching pulmonology too late',
    priority: 'Medium',
    lpRefs: ['LP4'], moRefs: ['MO4'],
    recurrence: 2,
    recency: '2026-05',
    summary: 'Rheumatologists want a clearer HRCT/PFT screening trigger for early pulmonology referral in systemic sclerosis; current practice is inconsistent and often delayed until symptomatic decline.',
    sourceInsights: [
      { type: 'Ad board', role: 'Rheumatologist', location: 'London, UK', quote: 'We need a screening algorithm we can actually put in front of general rheumatologists, not just EUSTAR specialists.', date: '2026-05-14' },
      { type: 'MSL interaction', role: 'Rheumatologist', location: 'Houston, TX', quote: 'By the time a patient gets to pulmonology, FVC has often already dropped meaningfully.', date: '2026-05-26' },
    ],
    status: 'Validated',
    confidenceScore: 0.76,
    provenance: 'synthesized',
  },
  {
    id: 'AI5',
    title: 'Mechanistic confusion: inhaled antifibrotic vs. inhaled prostacyclin',
    priority: 'Medium',
    lpRefs: ['LP5'], moRefs: ['MO5'],
    recurrence: 2,
    recency: '2026-06',
    summary: 'Community physicians and even some KOLs conflate AP01/AP02 with inhaled treprostinil (Tyvaso, TPIP) because both are described as "inhaled" — differentiation of mechanism and target population is not landing.',
    sourceInsights: [
      { type: 'Congress debrief', role: 'Pulmonologist', location: 'ATS 2026 satellite symposium', quote: 'Are you the same as the inhaled Tyvaso data everyone\'s talking about? I thought this was a different drug class.', date: '2026-05-19' },
      { type: 'MSL interaction', role: 'Community pulmonologist', location: 'Falls Church, VA', quote: 'Genuinely unclear from the poster titles alone whether inhaled means antifibrotic or vasodilator this year.', date: '2026-06-02' },
    ],
    status: 'Triaged',
    confidenceScore: 0.68,
    provenance: 'synthesized',
  },
  {
    id: 'AI6',
    title: 'Nerandomilast approval reshaping first-line IPF conversations',
    priority: 'High',
    lpRefs: ['LP6'], moRefs: ['MO5'],
    recurrence: 3,
    recency: '2026-06',
    summary: 'Following nerandomilast (Jascayd) approvals in IPF (Oct 2025) and PPF (Dec 2025), pulmonologists are actively asking how AP02 would sequence or compare against a genuinely new oral mechanism — not just against Ofev.',
    sourceInsights: [
      { type: 'MSL interaction', role: 'Academic pulmonologist', location: 'New Haven, CT', quote: 'Now that there\'s a real new oral mechanism, why would I wait for an inhaled reformulation of an old one?', date: '2026-06-12' },
      { type: 'Ad board', role: 'Community pulmonologist', location: 'Denver, CO', quote: 'I need to understand where an inhaled option fits once PDE4B inhibition is on the table.', date: '2026-05-30' },
      { type: 'Congress debrief', role: 'Multiple attendees', location: 'ATS 2026', quote: 'Several sessions pivoted mid-Q&A to nerandomilast sequencing questions regardless of the scheduled topic.', date: '2026-05-18' },
    ],
    status: 'Validated',
    confidenceScore: 0.84,
    provenance: 'synthesized',
  },
  {
    id: 'AI7',
    title: 'ATLAS dose-response data underused in scientific exchange',
    priority: 'Low',
    lpRefs: ['LP1'], moRefs: ['MO1'],
    recurrence: 1,
    recency: '2026-05',
    summary: 'KOLs recall the ATLAS Ph1b dose-response signal (100mg BID near-stabilized FVC through 48 weeks) but MSL field reports show inconsistent use of it in scientific exchange — an underleveraged proof point ahead of MIST topline.',
    sourceInsights: [
      { type: 'MSL interaction', role: 'ILD center director', location: 'Ann Arbor, MI', quote: 'I bring up ATLAS myself because the MSL materials I\'ve seen don\'t lead with it.', date: '2026-05-08' },
    ],
    status: 'Captured',
    confidenceScore: 0.6,
    provenance: 'synthesized',
  },
];
