// KOL roster — Demo Brief §7.
// LUCA's core dataset. 18 real, verified KOLs: 12 pulmonology/ILD +
// 6 rheumatology/SSc-ILD (per RESEARCH_SUMMARY.md §5). Cross-indication
// cluster: Cottin, Distler, Khanna and Volkmann all touch both the
// pulmonology (IPF/PPF) and rheumatology (CTD-ILD/SSc-ILD) conversation —
// the signature LUCA query is "who bridges pulm and rheum on SSc-ILD?"

export const KOL_DATA = [
  // ── Pulmonology / ILD ────────────────────────────────────────────────────
  {
    id: 'kol-1',
    name: 'Kevin R. Flaherty',
    institution: 'University of Michigan',
    city: 'Ann Arbor',
    country: 'USA',
    region: 'North America',
    specialty: 'Pulmonology / ILD',
    influenceScore: 96,
    engagementTier: 'Tier 1',
    productAlignment: ['ap01', 'ap02'],
    subIndications: ['IPF', 'PPF'],
    sentiment: 'Advocate',
    sentimentTrend: 'stable',
    recentInteractions: 9,
    publications: 412,
    focusAreas: ['PPF Diagnostic Criteria', 'INBUILD Trial', 'Progressive Fibrosing ILD', 'Treatment Sequencing'],
    conferenceAppearances: 12,
    recommendedStrategy: 'INBUILD PI and the KOL most associated with the PPF diagnostic construct AP01 is built around. Prioritize for MIST steering-committee-adjacent engagement and ATS/ERS scientific exchange on PPF classification.',
  },
  {
    id: 'kol-2',
    name: 'Kevin K. Brown',
    institution: 'National Jewish Health',
    city: 'Denver',
    country: 'USA',
    region: 'North America',
    specialty: 'Pulmonology / ILD',
    influenceScore: 90,
    engagementTier: 'Tier 1',
    productAlignment: ['ap01', 'ap02'],
    subIndications: ['IPF', 'PPF'],
    sentiment: 'Advocate',
    sentimentTrend: 'stable',
    recentInteractions: 7,
    publications: 356,
    focusAreas: ['ILD Multidisciplinary Diagnosis', 'IPF Natural History', 'Clinical Trial Design'],
    conferenceAppearances: 10,
    recommendedStrategy: 'Longstanding ILD center-of-excellence voice. Engage on multidisciplinary-discussion pathways relevant to earlier CTD-ILD referral into MIST.',
  },
  {
    id: 'kol-3',
    name: 'Ganesh Raghu',
    institution: 'University of Washington',
    city: 'Seattle',
    country: 'USA',
    region: 'North America',
    specialty: 'Pulmonology / ILD',
    influenceScore: 97,
    engagementTier: 'Tier 1',
    productAlignment: ['ap01', 'ap02'],
    subIndications: ['IPF', 'PPF'],
    sentiment: 'Advocate',
    sentimentTrend: 'shifting toward',
    recentInteractions: 8,
    publications: 489,
    focusAreas: ['ATS/ERS/JRS/ALAT IPF Guidelines', 'Antifibrotic Therapy', 'Diagnostic Guideline Authorship'],
    conferenceAppearances: 14,
    recommendedStrategy: 'IPF guideline chair — the single highest-leverage voice for how inhaled antifibrotics get positioned in future guideline revisions. Top-priority advisory board candidate.',
  },
  {
    id: 'kol-4',
    name: 'Toby M. Maher',
    institution: 'USC / Keck School of Medicine',
    city: 'Los Angeles',
    country: 'USA',
    region: 'North America',
    specialty: 'Pulmonology / ILD',
    influenceScore: 93,
    engagementTier: 'Tier 1',
    productAlignment: ['ap01', 'ap02'],
    subIndications: ['IPF', 'PPF', 'CTD-ILD'],
    sentiment: 'Advocate',
    sentimentTrend: 'stable',
    recentInteractions: 10,
    publications: 398,
    focusAreas: ['Novel Antifibrotic Mechanisms', 'PPF', 'Clinical Trial Leadership', 'CTD-ILD'],
    conferenceAppearances: 13,
    recommendedStrategy: 'Broad ILD trialist active across IPF, PPF and CTD-ILD — natural bridge KOL for AP01\'s cross-indication story. High interaction volume this cycle.',
  },
  {
    id: 'kol-5',
    name: 'Fernando J. Martinez',
    institution: 'Weill Cornell Medicine',
    city: 'New York',
    country: 'USA',
    region: 'North America',
    specialty: 'Pulmonology / ILD',
    influenceScore: 89,
    engagementTier: 'Tier 2',
    productAlignment: ['ap01', 'ap02'],
    subIndications: ['IPF', 'PPF'],
    sentiment: 'Neutral',
    sentimentTrend: 'stable',
    recentInteractions: 5,
    publications: 341,
    focusAreas: ['IPF Epidemiology', 'Antifibrotic Real-World Evidence', 'COPD-ILD Overlap'],
    conferenceAppearances: 9,
    recommendedStrategy: 'Wants outcomes and epidemiology framing rather than mechanism. Engage with MIST enrollment/design detail once available; currently neutral pending data.',
  },
  {
    id: 'kol-6',
    name: 'Luca Richeldi',
    institution: 'University of Southampton',
    city: 'Southampton',
    country: 'United Kingdom',
    region: 'Europe',
    specialty: 'Pulmonology / ILD',
    influenceScore: 95,
    engagementTier: 'Tier 1',
    productAlignment: ['ap01', 'ap02'],
    subIndications: ['IPF', 'PPF'],
    sentiment: 'Advocate',
    sentimentTrend: 'stable',
    recentInteractions: 6,
    publications: 445,
    focusAreas: ['FIBRONEER-IPF', 'Novel Antifibrotic Trial Design', 'IPF Phase 3 Leadership'],
    conferenceAppearances: 11,
    recommendedStrategy: 'FIBRONEER-IPF lead investigator — deeply versed in what differentiates a new antifibrotic mechanism from tolerability improvements on an old one. Key voice for AP02\'s "same mechanism, better route" narrative at ERS.',
  },
  {
    id: 'kol-7',
    name: 'Vincent Cottin',
    institution: 'Hôpital Louis Pradel, Hospices Civils de Lyon',
    city: 'Lyon',
    country: 'France',
    region: 'Europe',
    specialty: 'Pulmonology / ILD',
    influenceScore: 92,
    engagementTier: 'Tier 1',
    productAlignment: ['ap01', 'ap02'],
    subIndications: ['IPF', 'PPF', 'CTD-ILD', 'SSc-ILD'],
    sentiment: 'Advocate',
    sentimentTrend: 'shifting toward',
    recentInteractions: 8,
    publications: 467,
    focusAreas: ['Fibrosing ILD Spectrum', 'PPF Definition', 'CTD-ILD', 'Rare ILD Phenotypes'],
    conferenceAppearances: 12,
    recommendedStrategy: 'Cross-indication bridge KOL — one of the few voices credible in both fibrosing-ILD pulmonology and CTD-ILD referral pathways. Central to the LP1/LP4 referral-pathway narrative; co-presents pulm and rheum sessions.',
  },
  {
    id: 'kol-8',
    name: 'Steven D. Nathan',
    institution: 'Inova Fairfax Hospital',
    city: 'Falls Church, VA',
    country: 'USA',
    region: 'North America',
    specialty: 'Pulmonology / ILD',
    influenceScore: 91,
    engagementTier: 'Tier 2',
    productAlignment: ['ap02'],
    subIndications: ['IPF'],
    sentiment: 'Skeptic',
    sentimentTrend: 'shifting away',
    recentInteractions: 4,
    publications: 372,
    focusAreas: ['Inhaled Therapy in IPF', 'TETON Program (Tyvaso)', 'Pulmonary Hypertension-ILD Overlap', 'Lung Transplant'],
    conferenceAppearances: 10,
    recommendedStrategy: 'TETON-1/TETON-2 principal investigator for competitor inhaled treprostinil — the KOL most likely to conflate or directly compare an inhaled antifibrotic against inhaled prostacyclin. High-priority mechanism-differentiation conversation before ATS.',
  },
  {
    id: 'kol-9',
    name: 'Naftali Kaminski',
    institution: 'Yale School of Medicine',
    city: 'New Haven, CT',
    country: 'USA',
    region: 'North America',
    specialty: 'Pulmonology / ILD',
    influenceScore: 88,
    engagementTier: 'Tier 2',
    productAlignment: ['ap01', 'ap02'],
    subIndications: ['IPF', 'PPF'],
    sentiment: 'Neutral',
    sentimentTrend: 'stable',
    recentInteractions: 3,
    publications: 520,
    focusAreas: ['ILD Molecular Biomarkers', 'Genomics of Fibrosis', 'Precision Medicine in IPF'],
    conferenceAppearances: 8,
    recommendedStrategy: 'Biomarker-first thinker; low near-term engagement. Best approached with translational/mechanistic data package once AURA-IPF biomarker sub-analyses exist.',
  },
  {
    id: 'kol-10',
    name: 'Ivan O. Rosas',
    institution: 'Brigham and Women\'s Hospital / Harvard Medical School',
    city: 'Boston, MA',
    country: 'USA',
    region: 'North America',
    specialty: 'Pulmonology / ILD',
    influenceScore: 87,
    engagementTier: 'Tier 2',
    productAlignment: ['ap01', 'ap02'],
    subIndications: ['IPF', 'PPF', 'CTD-ILD'],
    sentiment: 'Emerging',
    sentimentTrend: 'shifting toward',
    recentInteractions: 5,
    publications: 334,
    focusAreas: ['ILD Biomarkers', 'CTD-ILD', 'Fibrosis Progression Modeling'],
    conferenceAppearances: 9,
    recommendedStrategy: 'Recently more vocal on inhaled-delivery rationale in scientific-exchange settings. Good near-term advisory-board candidate given rising interaction cadence.',
  },
  {
    id: 'kol-11',
    name: 'Talmadge E. King, Jr.',
    institution: 'UCSF',
    city: 'San Francisco, CA',
    country: 'USA',
    region: 'North America',
    specialty: 'Pulmonology / ILD',
    influenceScore: 90,
    engagementTier: 'Tier 2',
    productAlignment: ['ap01', 'ap02'],
    subIndications: ['IPF', 'PPF'],
    sentiment: 'Neutral',
    sentimentTrend: 'stable',
    recentInteractions: 2,
    publications: 401,
    focusAreas: ['IPF Landmark Trials', 'Antifibrotic Therapy History', 'Academic Leadership'],
    conferenceAppearances: 7,
    recommendedStrategy: 'Legacy IPF trialist with deep institutional credibility but low current interaction cadence. Re-engagement recommended ahead of ATS 2026.',
  },
  {
    id: 'kol-12',
    name: 'Paul W. Noble',
    institution: 'Cedars-Sinai Medical Center',
    city: 'Los Angeles, CA',
    country: 'USA',
    region: 'North America',
    specialty: 'Pulmonology / ILD',
    influenceScore: 91,
    engagementTier: 'Tier 2',
    productAlignment: ['ap01', 'ap02'],
    subIndications: ['IPF', 'PPF'],
    sentiment: 'Neutral',
    sentimentTrend: 'stable',
    recentInteractions: 3,
    publications: 415,
    focusAreas: ['IPF Pathobiology', 'Fibrosis Mechanisms', 'Antifibrotic Drug Development'],
    conferenceAppearances: 8,
    recommendedStrategy: 'Mechanistic-biology-first KOL. Interested in the fibrosis pathobiology rationale for pirfenidone/nintedanib reformulation more than the delivery-convenience story.',
  },

  // ── Rheumatology / SSc-ILD ───────────────────────────────────────────────
  {
    id: 'kol-13',
    name: 'Oliver Distler',
    institution: 'University Hospital Zurich',
    city: 'Zurich',
    country: 'Switzerland',
    region: 'Europe',
    specialty: 'Rheumatology / SSc-ILD',
    influenceScore: 96,
    engagementTier: 'Tier 1',
    productAlignment: ['ap01'],
    subIndications: ['SSc-ILD', 'CTD-ILD'],
    sentiment: 'Advocate',
    sentimentTrend: 'shifting toward',
    recentInteractions: 7,
    publications: 478,
    focusAreas: ['SENSCIS Trial', 'EUSTAR Registry', 'SSc-ILD Screening', 'Nintedanib in SSc-ILD'],
    conferenceAppearances: 13,
    recommendedStrategy: 'SENSCIS PI and EUSTAR leadership — the single most important rheumatology voice for AP01\'s SSc-ILD positioning. Top-priority EULAR advisory board candidate; already engaged on AP01 CTD-ILD data presented at EULAR 2025/2026.',
  },
  {
    id: 'kol-14',
    name: 'Dinesh Khanna',
    institution: 'University of Michigan',
    city: 'Ann Arbor, MI',
    country: 'USA',
    region: 'North America',
    specialty: 'Rheumatology / SSc-ILD',
    influenceScore: 93,
    engagementTier: 'Tier 1',
    productAlignment: ['ap01'],
    subIndications: ['SSc-ILD', 'CTD-ILD'],
    sentiment: 'Advocate',
    sentimentTrend: 'stable',
    recentInteractions: 6,
    publications: 452,
    focusAreas: ['Systemic Sclerosis Outcome Measures', 'SSc-ILD Trial Design', 'Scleroderma Clinical Trials Consortium'],
    conferenceAppearances: 11,
    recommendedStrategy: 'Co-located with Kevin Flaherty at Michigan — a natural rheum-pulm co-management pairing worth featuring in LP4 referral-pathway materials. High-value US advisory voice.',
  },
  {
    id: 'kol-15',
    name: 'Elizabeth R. Volkmann',
    institution: 'UCLA',
    city: 'Los Angeles, CA',
    country: 'USA',
    region: 'North America',
    specialty: 'Rheumatology / SSc-ILD',
    influenceScore: 88,
    engagementTier: 'Tier 2',
    productAlignment: ['ap01'],
    subIndications: ['SSc-ILD'],
    sentiment: 'Advocate',
    sentimentTrend: 'shifting toward',
    recentInteractions: 5,
    publications: 289,
    focusAreas: ['SSc-ILD Progression Monitoring', 'Immunosuppression vs Antifibrotic Sequencing', 'Patient-Reported Outcomes'],
    conferenceAppearances: 9,
    recommendedStrategy: 'Focused on sequencing questions (immunosuppression vs. antifibrotic) that AP01 needs a clear position on. Good candidate for a sequencing-focused scientific exchange ahead of EULAR.',
  },
  {
    id: 'kol-16',
    name: 'Christopher P. Denton',
    institution: 'UCL / Royal Free Hospital',
    city: 'London',
    country: 'United Kingdom',
    region: 'Europe',
    specialty: 'Rheumatology / SSc-ILD',
    influenceScore: 92,
    engagementTier: 'Tier 1',
    productAlignment: ['ap01'],
    subIndications: ['SSc-ILD', 'CTD-ILD'],
    sentiment: 'Advocate',
    sentimentTrend: 'stable',
    recentInteractions: 6,
    publications: 461,
    focusAreas: ['Systemic Sclerosis Natural History', 'SSc-ILD Screening Algorithms', 'Vascular & Fibrotic Complications'],
    conferenceAppearances: 10,
    recommendedStrategy: 'London-based and EULAR-local — natural host-market voice for the 2026 EULAR Congress. Strong candidate for a screening-algorithm co-authorship discussion tied to LP4.',
  },
  {
    id: 'kol-17',
    name: 'Maureen D. Mayes',
    institution: 'UTHealth Houston',
    city: 'Houston, TX',
    country: 'USA',
    region: 'North America',
    specialty: 'Rheumatology / SSc-ILD',
    influenceScore: 85,
    engagementTier: 'Tier 2',
    productAlignment: ['ap01'],
    subIndications: ['SSc-ILD'],
    sentiment: 'Neutral',
    sentimentTrend: 'stable',
    recentInteractions: 3,
    publications: 298,
    focusAreas: ['Scleroderma Epidemiology', 'SSc Genetics', 'Registry-Based Research'],
    conferenceAppearances: 7,
    recommendedStrategy: 'Registry/epidemiology-first orientation. Engage with population-level screening-gap data rather than single-agent efficacy framing.',
  },
  {
    id: 'kol-18',
    name: 'Francesco Del Galdo',
    institution: 'University of Leeds',
    city: 'Leeds',
    country: 'United Kingdom',
    region: 'Europe',
    specialty: 'Rheumatology / SSc-ILD',
    influenceScore: 84,
    engagementTier: 'Tier 2',
    productAlignment: ['ap01'],
    subIndications: ['SSc-ILD', 'CTD-ILD'],
    sentiment: 'Emerging',
    sentimentTrend: 'shifting toward',
    recentInteractions: 4,
    publications: 267,
    focusAreas: ['EUSTAR', 'Skin & Lung Fibrosis Biomarkers', 'Early SSc Detection'],
    conferenceAppearances: 8,
    recommendedStrategy: 'EUSTAR-affiliated with rising publication cadence on early-detection biomarkers. Emerging-voice watch-list candidate — appropriate for MSL-led early engagement ahead of Tier 1 promotion.',
  },
];
